FROM python:3.12

USER root
RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
RUN apt -y update && apt -y upgrade

WORKDIR /backend_fastapi

COPY ./backend_fastapi/requirements.txt .

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend_fastapi .

CMD ["python", "app.py"]